"""empty message

Revision ID: 1b6d25b63872
Revises: None
Create Date: 2016-03-30 00:17:54.302538

"""

# revision identifiers, used by Alembic.
revision = '1b6d25b63872'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
