"""update Role Permission

Revision ID: 3bd9b6113344
Revises: add7c895d078
Create Date: 2016-06-20 23:55:11.556147

"""

# revision identifiers, used by Alembic.
revision = '3bd9b6113344'
down_revision = 'add7c895d078'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
