"""empty message

Revision ID: e38be5b6833
Revises: 1b6d25b63872
Create Date: 2016-03-30 00:18:48.066412

"""

# revision identifiers, used by Alembic.
revision = 'e38be5b6833'
down_revision = '1b6d25b63872'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test')
    ### end Alembic commands ###
